export const projects = [
    {
      title: 'YourFitnessFriend',
      description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it",
        image: 'https://1000logos.net/wp-content/uploads/2020/09/JavaScript-Logo.png',
        tags: ['Mongo', 'Express', 'React', 'Node'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 0,
    },
    {
      title: 'Pro-active',
      description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video",
      image: 'https://imgur.com/r80auoK',
      tags: ['React', 'JavaScript'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 1,
    },
    {
      title: 'MovieBuddy',
      description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
      image: 'https://imgur.com/r80auoK',
        tags: ['React', 'WebRTC'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 2,
    },
    {
      title: 'Reactr',
      description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
      image: 'https://imgur.com/r80auoK',
      tags: ['React', 'ChatEngine', 'Firebase'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 3,
    },
    {
      title: 'ApartmentConnect',
      description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
      image: 'https://imgur.com/r80auoK',
      tags: ['React', 'ChatEngine', 'Firebase'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 4,
    }
  ];